package com.model;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class TOrder implements java.io.Serializable
{
	private Integer id;
	private String bianhao;
	private String xiadanshi;
	private String userName;
	
	private String userRealname;
	private String userTel;
	private String songhuodizhi;
	private String fukuanfangshi;
	
	private int jine;
	private String zhuangtai;
	private Integer userId;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getBianhao() {
		return bianhao;
	}
	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}
	public String getXiadanshi() {
		return xiadanshi;
	}
	public void setXiadanshi(String xiadanshi) {
		this.xiadanshi = xiadanshi;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public String getUserRealname() {
		return userRealname;
	}
	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}
	
	public String getUserTel() {
		return userTel;
	}
	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}
	public String getSonghuodizhi() {
		return songhuodizhi;
	}
	public void setSonghuodizhi(String songhuodizhi) {
		this.songhuodizhi = songhuodizhi;
	}
	
	public String getFukuanfangshi() {
		return fukuanfangshi;
	}
	public void setFukuanfangshi(String fukuanfangshi) {
		this.fukuanfangshi = fukuanfangshi;
	}
	public int getJine() {
		return jine;
	}
	public void setJine(int jine) {
		this.jine = jine;
	}
	public String getZhuangtai() {
		return zhuangtai;
	}
	public void setZhuangtai(String zhuangtai) {
		this.zhuangtai = zhuangtai;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}